<?php
echo '';
echo '';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '';
echo '<!-- meta tags -->';
echo '<meta charset="utf-8">';
echo '<meta name="keywords" content="Bunduq Company Limited" />';
echo '<meta name="description" content="Bunduq Company Limited" />';
echo '<meta name="author" content="www.Bunduq.com" />';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '';
echo '<!-- Title -->';
echo '<title> Bunduq | Career</title>';
echo '';
echo '<!-- favicon icon -->';
echo '<link rel="shortcut icon" href="images/favicon.ico" />';
echo '';
echo '<!-- inject css start -->';
echo '';
echo '<!--== bootstrap -->';
echo '<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!--== animate -->';
echo '<link href="css/animate.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!--== fontawesome -->';
echo '<link href="css/fontawesome-all.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!--== themify-icons -->';
echo '<link href="css/themify-icons.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!--== magnific-popup -->';
echo '<link href="css/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!--== owl-carousel -->';
echo '<link href="css/owl-carousel/owl.carousel.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!--== spacing -->';
echo '<link href="css/spacing.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!--== base -->';
echo '<link href="css/base.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!--== shortcodes -->';
echo '<link href="css/shortcodes.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!--== default-theme -->';
echo '<link href="css/style.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!--== responsive -->';
echo '<link href="css/responsive.css" rel="stylesheet" type="text/css" />';
echo '';
echo '<!-- inject css end -->';
echo '';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<!-- page wrapper start -->';
echo '';
echo '<div class="page-wrapper">';
echo '';
echo '<!-- preloader start -->';
echo '';
echo '<div id="ht-preloader">';
echo '<div class="loader clear-loader"><img src="images/loader.gif" alt=""></div>';
echo '</div>';
echo '';
echo '<!-- preloader end -->';
echo '';
echo '';
echo '<!--header start-->';
echo '';
echo '<header id="site-header" class="header">';
echo '<div class="top-bar d-sm-block d-none">';
echo '<div class="container">';
echo '<div class="row align-items-center">';
echo '<div class="col-md-4">';
echo '<div class="topbar-link d-md-block d-none">';
echo '<ul class="list-inline">';
echo '<li class="list-inline-item"><a href="mailto:contact@bunduq.com"><i class="far fa-envelope-open"></i>info@bunduq.ae</a>';
echo '</li>';
echo '<li class="list-inline-item">';
echo '<a href="tel:+97124035335"> <i class="fas fa-mobile-alt"></i>+971 2 403 5335</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4 col-sm-6 text-center">';
echo '';
echo '</div>';
echo '<div class="col-md-4 col-sm-6 text-end">';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div id="header-wrap">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col">';
echo '<!-- Navbar -->';
echo '<nav class="navbar navbar-expand-lg">';
echo '<a class="navbar-brand logo" href="index.html">';
echo '<img id="logo-img" class="img-fluid" src="images/logo.png" alt="">';
echo '</a>';
echo '<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarNavDropdown">';
echo '<!-- Left nav -->';
echo '<ul class="nav navbar-nav ms-auto">';
echo '<li class="nav-item"> <a class="nav-link " href="index.html" data-bs-toggle="">Home</a>';
echo '</li>';
echo '<li class="nav-item "> <a class="nav-link " href="about.html" data-bs-toggle="">About</a>';
echo '</li>';
echo '<li class="nav-item "> <a class="nav-link " href="operations.html" data-bs-toggle="">Operations</a>';
echo '</li>';
echo '<li class="nav-item  position-static"> <a class="nav-link " href="media.html" data-bs-toggle="">Media</a>';
echo '</li>';
echo '<li class="nav-item "> <a class="nav-link  active " href="careers.html" data-bs-toggle="">Careers</a>';
echo '</li>';
echo '<li class="nav-item "> <a class="nav-link " href="contact.html" data-bs-toggle="">Contact</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '';
echo '<!--header end-->';
echo '';
echo '';
echo '<!--page title start-->';
echo '';
echo '<section class="page-title overflow-hidden text-center parallaxie" data-overlay="7" data-bg-img="images/bg/16.jpg">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8 col-md-12 mx-auto">';
echo '<h1 class="title mb-0">Bunduq <span>Careers</span></h1>';
echo '</div>';
echo '</div>';
echo '<nav aria-label="breadcrumb" class="page-breadcrumb">';
echo '<ol class="breadcrumb">';
echo '<li class="breadcrumb-item"><a href="index.html"><i class="fas fa-home"></i></a>';
echo '</li>';
echo '<li class="breadcrumb-item active" aria-current="page">Careers</li>';
echo '</ol>';
echo '</nav>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<!--page title end-->';
echo '';
echo '';
echo '<!--body content start-->';
echo '';
echo '<div class="page-content">';
echo '';
echo '<!--about start-->';
echo '';
echo '<section>';
echo '<div class="container">';
echo '<div class="row align-items-center">';
echo '';
echo '<div class="col-lg-12 col-md-12 mt-3 mt-lg-0">';
echo '<h2 class="title">Application Submitted  <span>Successfully</span></h2>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
echo '</div>';
echo '';
echo '<!--body content end-->';
echo '';
echo '';
echo '<!--footer start-->';
echo '';
echo '<footer class="footer dark-bg position-relative" data-bg-img="images/bg/09.png" style="background-size: contain; background-repeat: no-repeat;">';
echo '';
echo '<div class="primary-footer">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-3 col-md-6">';
echo '<div class="footer-circlelogo">';
echo '<a href="index.html"><img src="images/logo-circle.png" style="width:100%;"></a>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 mt-5 mt-md-0 footer-list">';
echo '<h5>Quick <span class="text-theme"> Links</span></h5>';
echo '<ul class="list-unstyled">';
echo '<li><a href="operations.html"><i class="fas fa-angle-right"></i>Operations Overview</a>';
echo '</li>';
echo '<li><a href="media.html"><i class="fas fa-angle-right"></i> News & Media</a>';
echo '</li>';
echo '';
echo '';
echo '<li><a href="hse"><i class="fas fa-angle-right"></i> HSE Activities</a>';
echo '</li>';
echo '<li><a href="contact.html"><i class="fas fa-angle-right"></i> Contact</a>';
echo '</li>';
echo '';
echo '</ul>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 mt-5 mt-lg-0 widget">';
echo '<h5>Recent <span class="text-theme"> News</span></h5>';
echo '<div class="recent-post mb-0">';
echo '<ul class="list-unstyled">';
echo '<li class="mb-3">';
echo '<div class="recent-post-thumb">';
echo '<img class="img-fluid" src="images/blog/blog-thumb/01.jpg" alt="">';
echo '</div>';
echo '<div class="recent-post-desc"> <a href="#">Qatarization Crystal Award</a>';
echo '<span>May 20, 2020</span>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div class="recent-post-thumb">';
echo '<img class="img-fluid" src="images/blog/blog-thumb/02.jpg" alt="">';
echo '</div>';
echo '<div class="recent-post-desc"> <a href="#">Remaining Life Assessment (RLA) Study </a>';
echo '<span>March 14, 2021</span>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 mt-5 mt-lg-0">';
echo '<h5>Reach <span class="text-theme"> Us</span></h5>';
echo '<a href="https://goo.gl/maps/191ptLRjj29nicb86" class=" btn btn-sm btn-border btn-radius mb-2" target="_blank">Follow the Directions</a>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="secondary-footer">';
echo '<div class="container">';
echo '<div class="copyright">';
echo '<div class="row align-items-center">';
echo '<div class="col-md-7"> <span>Copyright 2022  <a target="_blank" href="www.bunduq.com"> Bunduq Company Limited </a> | All Rights Reserved</span>';
echo '</div>';
echo '<div class="col-md-5 text-md-end mt-3 mt-md-0 footer-list">';
echo '<ul class="list-inline">';
echo '<li><a href="terms-and-conditions.html">Terms & Condition</a>';
echo '</li>';
echo '<li><a href="privacy-policy.html">Privacy Policy</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '';
echo '<!--footer end-->';
echo '';
echo '';
echo '</div>';
echo '';
echo '<!--page wrapper end-->';
echo '';
echo '<!-- get a quote start -->';
echo '';
echo '';
echo '<!-- get a quote end -->';
echo '';
echo '';
echo '';
echo '';
echo '<!--back-to-top start-->';
echo '';
echo '<div class="scroll-top"><a class="smoothscroll" href="#top"><i class="fas fa-chevron-up"></i></a></div>';
echo '';
echo '<!--back-to-top end-->';
echo '';
echo '';
echo '<!-- inject js start -->';
echo '';
echo '<!--== theme -->';
echo '<script src="js/theme.js"></script>';
echo '';
echo '<!--== magnific-popup -->';
echo '<script src="js/magnific-popup/jquery.magnific-popup.min.js"></script>';
echo '';
echo '<!--== owl-carousel -->';
echo '<script src="js/owl-carousel/owl.carousel.min.js"></script>';
echo '';
echo '<!--== parallax -->';
echo '<script src="js/parallax/parallaxie.min.js"></script>';
echo '';
echo '<!--== counter -->';
echo '<script src="js/counter/counter.js"></script>';
echo '';
echo '<!--== particle -->';
echo '<script src="js/particle/jquery.particleground.min.js"></script>';
echo '';
echo '<!--== countdown -->';
echo '<script src="js/countdown/jquery.countdown.min.js"></script>';
echo '';
echo '<!--== isotope -->';
echo '<script src="js/isotope/isotope.pkgd.min.js"></script>';
echo '';
echo '<!--== contact-form -->';
echo '<script src="js/contact-form/contact-form.js"></script>';
echo '';
echo '<!--== theme-script -->';
echo '<script src="js/theme-script.js"></script>';
echo '';
echo '<!-- inject js end -->';
echo '';
echo '';
echo '<!-- <script>';
echo '$(document).ready(function() {';
echo '$(document).bind("contextmenu", function(e) {';
echo 'return false;';
echo '});';
echo '});';
echo '</script>';
echo '-->';
echo '';
echo '</body>';
echo '';
echo '</html>';
echo '';
echo '?>';
?>